name: Build msiparse via Rust

on:
  workflow_dispatch: {} # Manual trigger
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    name: Release - ${{ matrix.platform.target }}
    strategy:
      matrix:
        platform:
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            skip_tests: true
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            skip_tests: true
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Build only the CLI using the build script
      - name: Run build script (CLI only)
        run: python build.py --cli-only

      # Upload the Rust binary
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: msiparse-${{ matrix.platform.target }}
          path: |
            target/release/msiparse*
            !target/release/msiparse.d
